spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testcontainers_demo
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
